services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "MyStrongPass123"
      MSSQL_PID: "Developer"
      MSSQL_USER: "SA"
  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"
  mail:
    image: jijiechen/papercut:latest
    container_name: papercut
    ports:
      - "25:25"
      - "37408:37408"
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"